In [2]:
import numpy

In [7]:
# create one dimensional array
one=numpy.arange(27)
one

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [9]:
# convert the created array into 2 dimensions with .reshape(rows,columns) method
two=one.reshape(3,9)
two

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [11]:
# convert the created array into 3 dimensions with .reshape(rows,columns,z) method
three=two.reshape(3,3,3)
three

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
# convert a list into an array with .asarray() method
array=numpy.asarray([[123,12,123,12,33],[],[]])
array

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [16]:
import cv2

In [20]:
# load an image with cvs2.imread(path,number) (0 for black&white and 1 for color)
img=cv2.imread("smallgray.png",0)
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [25]:
# index a numpy array and access its portions
img[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [27]:
# iterate through a numpy array
# iterate through rows
for i in img:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [30]:
# iterate through columns with .T 
for i in img.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [31]:
# iterate through every value of the array with .flat
for i in img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
