In [2]:
import numpy

In [7]:
# create one dimensional array
one=numpy.arange(27)
one

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [9]:
# convert the created array into 2 dimensions with .reshape(rows,columns) method
two=one.reshape(3,9)
two

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [11]:
# convert the created array into 3 dimensions with .reshape(rows,columns,z) method
three=two.reshape(3,3,3)
three

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
# convert a list into an array with .asarray() method
array=numpy.asarray([[123,12,123,12,33],[],[]])
array

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)